// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  t113s3proSidebar: [{type: 'autogenerated', dirName: 'T113s3-Pro'}],
  d1dSidebar: [{type: 'autogenerated', dirName: 'D1-Nezha'}],  
  t113iSidebar: [{type: 'autogenerated', dirName: 'T113i-Industrial'}],
  t113s3sdnandSidebar: [{type: 'autogenerated', dirName: 'T113s3-SdNand'}],
  t113s4sdnandSidebar: [{type: 'autogenerated', dirName: 'T113s4-SdNand'}],
  a133Sidebar: [{type: 'autogenerated', dirName: 'A133-mCore'}],
  h616Sidebar: [{type: 'autogenerated', dirName: 'H616-YuzukiHD'}],
  t527Sidebar: [{type: 'autogenerated', dirName: 'T527-AvaotaA1'}],
  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
